kind: workload
name: app
spec:
  type: serverless
  containers:
    - name: app
      image: seanodea-5f382d.registry.cpln.io/chordhound:latest
      ports:
        - number: 8000
          protocol: http
      cpu: 500m
      memory: 512Mi
      env:
        - name: APP_ENV
          value: production
        - name: APP_DEBUG
          value: "false"
        - name: LOG_CHANNEL
          value: stderr
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
  defaultOptions:
    autoscaling:
      minScale: 1
      maxScale: 5
      metric: concurrency
      target: 100
      maxConcurrency: 1000
    capacityAI: false
    debug: false
    suspend: false
    timeoutSeconds: 60
  firewallConfig:
    external:
      inboundAllowCIDR:
        - 0.0.0.0/0
      outboundAllowCIDR:
        - 0.0.0.0/0
    internal:
      inboundAllowType: same-org
